version: '3.8'

services:
  backend:
    image: "{{ backend_image }}"
    container_name: online_exam_backend
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=super_secret_key
    networks:
      - online-exam-network

  frontend:
    image: "{{ frontend_image }}"
    container_name: online_exam_frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE=http://backend:8080
    depends_on:
      - backend
    networks:
      - online-exam-network

networks:
  online-exam-network:
    driver: bridge
